import Head from 'next/head'
import {useCallback} from "react";
import {useRouter} from 'next/router';
import Footer from "../components/Footer";
import Separator from "../components/Seperator";

const articlesList = [
	{
		title: 'Hiking through the woods',
		date: 'Jan 08, 2019',
		description: 'This is RichText that includes both external links and links to internal documents. They should be handled intelligently or everything might break. Don\'t forget about media too! Do your best to solve this using HTML Serializer. We shall now test image links as well:'
	},
	{
		title: 'Beach resort vacation',
		date: 'Jan 08, 2019',
		description: 'Nothing beats the experience and comfort of relaxing at the beach. Specially given that lorem ipsum dolor sit amet, eum in quas soluta altera, his everti albucius et. Ex ius sint repudiare. No eum lorem minim novum, quo eu ferri viderer, vix deleniti atomorum ad. Ad per viderer vituperata. Accusata...'
	},
	{
		title: 'Perilous yoga',
		date: 'Jan 08, 2019',
		description: 'Doing a good yoga routine will get you nice and limber for whatever crazy photo posing you have to do in your travels. However, lorem ipsum dolor sit amet, usu ne numquam eligendi, est id doming malorum. Te his altera diceret. Ne duo quodsi omnesque liberavisse, vel ignota mucius vivendo ne,...'
	}
];

export default function Home() {
	const router = useRouter()
	const handleClick = useCallback((articleTitle) => {
		router.push(`/blog/${articleTitle.replaceAll(' ', '-')}`)
	}, [])

	return (
		<div className='px-4 py-8 flex flex-col gap-10'>
			<Head>
				<title>Feet on the ground</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>

			<header className='flex flex-col items-center pt-6 pb-4'>
				<img className='w-[10rem] h-[10rem] rounded-full' src={'./image.jpg'} alt={'p'}/>
				<h2 className='text-4xl text-gray-900 font-bold my-4'>Feet on the ground</h2>
				<p className='text-gray-400 text-[1.1rem]'>Getting to know yourself by knowing the world</p>
			</header>

			<Separator/>

			<main className='flex flex-col gap-10'>
				{
					articlesList.map(article => (
							<div key={article.title} className='flex flex-col gap-0.5 items-start'>
								<h2 className='font-bold text-gray-700 text-[27px] cursor-pointer '
									onClick={() => handleClick(article.title)}>{article.title}</h2>
								<time className=' text-gray-400'>{article.date}</time>
								<p className='font-serif leading-relaxed text-[17px] text-gray-900'>{article.description}</p>
							</div>
						)
					)
				}
			</main>
			<Separator/>

			<Footer/>
		</div>
	)
}

